### ISSUE TITLE
Integration cannot load with polish Orange decoder

### ISSUE THREAD

**Issue by przemekpd** [AkA57/liveboxtvuhd#12]
I have tried to use liveboxtvuhd with polish Orange ICU 100 Decoder. After import by HACS and restart HA your component didn't load. With this error in log

Platform error media_player.liveboxtvuhd - cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)

I use HA 0.108.5 and liveboxtvuhd 0.0.7

Here is output of request http://192.168.1.85:8080/remoteControl/cmd?operation=10

{ "result": { "responseCode": "0", "message": "ok", "data": { "activeStandbyState": "0", "friendlyName": "Dekoder TV", "macAddress": "60:C5:AD:A2:08:17", "osdContext": "LIVE", "playedMediaContextId": "1", "playedMediaId": "14135", "playedMediaPosition": "NA", "playedMediaState": "PLAY", "playedMediaType": "LIVE", "timeShiftingState": "0", "wolSupport": "0" } } }

**Comment by AkA57** [comment]
Hello,
You're right, v0.0.7 need Home Assistant 0.110.
If you want to use it with  HA 0.108.5, you can try v0.0.5

**Comment by przemekpd** [comment]
Hello
after upgrade HA to the last version everything works fine.
Thank You

**Comment by AkA57** [comment]
Good to hear!
