### ISSUE TITLE
Perte de liaison avec la livebox TV

### ISSUE THREAD

**Issue by bennijamm** [AkA57/liveboxtvuhd#16]
Bonjour,
Je rencontre un problème avec ma livebox TV depuis quelques jours : je n'arrive plus à la pinguer, je n'y ai donc plus d'accès, ce qui fait que je ne peux plus la commander à distance. Ce n'est pas vraiment lié au plugin mais c'est comme ça que je m'en suis aperçu.
Avez-vous déjà eu ce genre de problème ? Avez-vous connaissance de mécanisme de sécurité de bannissement automatique par exemple ?
Merci, et merci pour ce plugin

**Comment by AkA57** [comment]
Bonjour,

Non il n'y a pas de mécanisme de bannissement à ma connaissance.
Est-ce que la TV fonctionne quand même, vous arrivez à regarder les chaines par ADSL ou Fibre?

Normalement en se connectant sur le routeur livebox, vous pouvez y afficher les équipements connectés et donc l'adresse IP du boitier TV.

[![decodeurtv.png](https://i.postimg.cc/7PMmLyY5/decodeurtv.png)](https://postimg.cc/kDGxjzSC)

**Comment by bennijamm** [comment]
Etrange, après un redémarrage de la livebox (pas la box TV), ça remarche...
Pour répondre aux questions, oui la TV fonctionne bien.
Je suis sur un réseau séparé du réseau natif de la Livebox et je me suis aperçu (avant le redémarrage de la Livebox) que le ping fonctionnait bien quand on était sur le même adressage que la box TV.
Je ne sais pas trop quoi en penser...
