### ISSUE TITLE
Version dans le manifest

### ISSUE THREAD

**Issue by bennijamm** [AkA57/liveboxtvuhd#17]
Bonjour,
Depuis la dernière release, il faut un n° de version dans le manifest.
J'ai ce message dans les logs :
`No 'version' key in the manifest file for custom integration 'liveboxtvuhd'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'liveboxtvuhd'`

Pourriez-vous faire qqc ?
Merci

**Comment by AkA57** [comment]
La version 1.0.1 est disponible avec la correction
