### ISSUE TITLE
Connection timeout when in deep sleep

### ISSUE THREAD

**Issue by Adorem** [AkA57/liveboxtvuhd#20]
Bonjour,

J'utilise la v1.0.1 avec Home Assistant core-2021.4.5.
Comme évoqué dans cet autre issue #13 lorsque que le décodeur est en deep sleep j'ai cette erreur dans les logs parce que le répondeur n'est pas dispo sur le réseau :

```
Logger: custom_components.liveboxtvuhd.client
Source: custom_components/liveboxtvuhd/client.py:336
Integration: liveboxtvuhd (documentation)
First occurred: 7:41:27 (276 occurrences)
Last logged: 8:27:20

HTTPConnectionPool(host='192.168.1.22', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f19079ef370>, 'Connection to 192.168.1.22 timed out. (connect timeout=3)'))
HTTPConnectionPool(host='192.168.1.22', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1908938550>, 'Connection to 192.168.1.22 timed out. (connect timeout=3)'))
HTTPConnectionPool(host='192.168.1.22', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f190894ca90>, 'Connection to 192.168.1.22 timed out. (connect timeout=3)'))
HTTPConnectionPool(host='192.168.1.22', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f19079efd90>, 'Connection to 192.168.1.22 timed out. (connect timeout=3)'))
HTTPConnectionPool(host='192.168.1.22', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1907947550>, 'Connection to 192.168.1.22 timed out. (connect timeout=3)'))
```

Pourtant ça semble être résolu ici #14 .

Est-ce que ça serait un problème de mon côté ?

**Comment by JLPH987** [comment]
Même problème ici
`2021-05-19 17:48:09 ERROR (SyncWorker_2) [custom_components.liveboxtvuhd.client] HTTPConnectionPool(host='192.168.1.2', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x66f8d418>, 'Connection to 192.168.1.2 timed out. (connect timeout=3)'))`
Avec le même log toutes les 10 secondes.

En revanche, j'ai constaté une mise à jour de la box il y a quelques jours (changement d'interface d'accueil). Peut-être que c'est cela qui a introduit le bug ?

**Comment by AkA57** [comment]
Bonjour,

En fait le composant liveboxtvuhd va vérifier l'état de la livebox toutes les X secondes, en fonction du paramétrage **scan_interval** que vous avez spécifié dans le fichier **configuration.yaml**.

Le problème avec le mode économie d'énergie de la livebox, c'est que celle-ci coupe complètement la communication réseau et donc elle n'est plus du tout joignable; d'où ces messages d'erreur.

La correction l'issue #13 , consistait justement a afficher une 1 ligne d'erreur propre dans les logs, plutôt qu'une stack python de 300 lignes à chaque interrogation.

Pour faire simple, je ne peux pas faire la différence entre une livebox en économie d'énergie que ne répond pas sur le réseau ou une mauvaise configuration au niveau de l'adresse IP, qui ne répondrait pas non plus.

Mais si vous avez des idées, n'hésitez pas à m'en faire part 😄
