### ISSUE TITLE
Cover is not displayed anymore

### ISSUE THREAD

**Issue by Jucgshu** [AkA57/liveboxtvuhd#21]
For some days, the integration works partially. I can see and switch channel, but cover is not diplayed anymore. Nothing has changed in my configuration.

![livebox](https://user-images.githubusercontent.com/3890387/121420616-94cccc80-c96d-11eb-9d82-8136095127f3.png)

I can see this kind of error message in the journal log.

`HTTPConnectionPool(host='192.168.1.19', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd492445d00>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Is there anything to check on my side?

**Comment by AkA57** [comment]
Hello,

You're right, EPG informations are not working anymore:
- Cover
- Show name
- Show time
- Season and episode

Thanks for this information, I will check quickly

**Comment by AkA57** [comment]
Bonjour,

La v1.0.2 corrige le problème.

L'EPG est récupéré depuis le site officiel d'orange woopic.com (un ancêtre signifiant **W**anad**oo** **pic**tures) et il semble qu'Orange ait voulu bloquer mon plugin.
A mon avis il y a de grande chance que cela se reproduise à l'avenir ;o)

En tout cas merci pour ce retour.

**Comment by Vebryn** [comment]
> Bonjour,
> 
> La v1.0.2 corrige le problème.
> 
> L'EPG est récupéré depuis le site officiel woopic.com (un ancêtre signifiant **W**anad**oo** **pic**tures) et il semble qu'Orange ait voulu bloquer mon plugin. A mon avis il y a de grande chance que cela se reproduise à l'avenir ;o)
> 
> En tout cas merci pour ce retour.

Effectivement, ça ne fonctionne plus. Avec un curl sur l'url et le user-agent spécifié :

```
curl -k -A "Opera/9.80 (Linux i686; U; fr) Presto/2.10.287 Version/12.00 ; SC/IHD92 STB" https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs -d '{"groupBy": "channel", "period": "current", "epgIds": 1, "mco": "OFR"}'
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

**Comment by AkA57** [comment]
Tiens c'est intéressant, je n'ai pas de problème de mon coté.

```
root@unraid:/# curl -k -A "Opera/9.80 (Linux i686; U; fr) Presto/2.10.287 Version/12.00 ; SC/IHD92 STB" "https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=197&mco=OFR"
{"197":[{"id":1642906954488,"programType":"OTHER","title":"Manger bouger dormir","channelId":"197","channelZappingNumber":106,"covers":[{"format":"RATIO_4_3","url":"https://proxymedia.woopic.com/340/p/43_COL_10894437.jpg"},{"format":"RATIO_16_9","url":"https://proxymedia.woopic.com/340/p/169_COL_10894437.jpg"}],"diffusionDate":1642958820,"duration":180,"csa":1,"synopsis":"Marcus mange n'importe quoi, reste des he...
```
Peut-être que c'est en cours de déploiement

**Comment by Vebryn** [comment]
bien vu, pas un proxy mais un dns custom que ne résoud pas le domaine. Avec le dns de la livebox ça passe bien, merci !
