### ISSUE TITLE
EPG response: 404 on Polish Orange Livebox

### ISSUE THREAD

**Issue by WRLPDZ** [AkA57/liveboxtvuhd#24]
Hello,

First of all, thank you for your work.

On Polish Livebox there is an error:
EPG response: 404 Client Error: Not Found for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=14171&mco=OFR

Web page response under this address is:
{"code":60,"message":"Resource not found","param":{},"description":"L'URI demandé ou la ressource demandée n'existe pas.","stackTrace":null}

If I delete last part of address there is list but not for Poland.
https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds
Result in uploaded file:
[programs.txt](https://github.com/AkA57/liveboxtvuhd/files/7875886/programs.txt)

Do You know is there such list for Poland?
Under this address I see only French addresses - https://rp-live-pc.woopic.com/live-webapp/v3/applications

Or how to check from where originally Polish livebox is getting EPG?
And how to implement it?

**Comment by AkA57** [comment]
Hello,

You're right, https://rp-live-pc.woopic.com is only for French channels.
I just have a look at how https://tvgo.orange.pl work, but I don't have an account.
By the way, I found something that looks like an api for epg.
Can you confirm "Kuba Wojewódzki" is playing on channel 14171 ?
```

   "channelExternalId": "14171",
   "schedule": [
    {
     "name": "Kuba Wojewódzki",
     "startDate": 1642205400,
     "endDate": 1642209000,
     "prLevel": "4",
     "referenceProgramId": "lid430888147636207",
     "episodeNumber": "6",
     "genre": "talk-show",
     "isSeries": true,
     "attributes": [
      "attr-16x9"
     ]
    },
    {
     "name": "MasterChef",
     "startDate": 1642209000,
     "endDate": 1642213500,
     "prLevel": "3",
     "referenceProgramId": "lid430888147636209",
     "episodeNumber": "7",
     "genre": "program rozrywkowy",
     "isSeries": true,
     "attributes": [
      "attr-16x9"
     ]
    },
```

**Comment by WRLPDZ** [comment]
Hi,

Yes channel 14171 is TVN HD.
[kanały-orange-tv.xlsx](https://github.com/AkA57/liveboxtvuhd/files/7876016/kanaly-orange-tv.xlsx)

**Comment by AkA57** [comment]
Thanks for the channels list !

I will try to provide a new version of liveboxtvuhd by adding a configuration key for choosing between French and Polish channels/epg.
Are you agree to do some test on it ?

**Comment by WRLPDZ** [comment]
Yes of course. I will participate in tests.

**Comment by AkA57** [comment]
Hello @WRLPDZ 

A new beta version is available with Polish support
![Capture d’écran 2022-01-16 221826](https://user-images.githubusercontent.com/42451111/149678436-d70db54c-a2da-4724-8364-45779d4e10df.png)

Can you please have a try ?

**Comment by WRLPDZ** [comment]
Hi

It stop error so that grate.

How did you make it show cover?

Whatever I set i have only black card.

niedz., 16 sty 2022, 22:19 użytkownik AkA57 ***@***.***>
napisał:

**Comment by AkA57** [comment]
Hi,

Good to hear.

Cover depend on channel.
Some channel provide it (like TVP 2 HD). Can you see it ?

![Capture d’écran 2022-01-17 200422](https://user-images.githubusercontent.com/42451111/149825167-5638e96e-4aec-4350-bf26-3a4740473b52.png)

**Comment by WRLPDZ** [comment]
It's not working for me, but it's not important now.

Error is gone so I close this topic.

Thank you for your quick help.
