### ISSUE TITLE
Avoid timed out logs

### ISSUE THREAD

**Issue by Vebryn** [AkA57/liveboxtvuhd#26]
Hello,

Great plugin, exactly what I was looking. A request to make it perfect :

I power off my TV UHD at night. So Home Assistant trigger a lot of errors :

```
HTTPConnectionPool(host='192.168.1.193', port=8080): Max retries exceeded with url: /remoteControl/cmd?operation=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x65ac9fd0>, 'Connection to 192.168.1.193 timed out. (connect timeout=3)'))
```

Instead of this error, is it possible to gray out mini player ? Or display a message at channel name or description ? User will see unavailable message.

Best regards.

**Comment by AkA57** [comment]
Hello,
Done on version 1.0.4.

The error message is now only displayed 1 time at HA startup, if the livebox is not available.
Please have some test and feel free to close this issue

Regards

**Comment by Vebryn** [comment]
I just update, great ! Thanks
