### ISSUE TITLE
Power ON button doesn't work

### ISSUE THREAD

**Issue by tifou92** [AkA57/liveboxtvuhd#30]
Hi,

Everything work fine with this integration but not thé POWER ON button. I can turn off the tv box but not turn it on.

Any idea?

Thanks,

**Comment by faizpuru** [comment]
+1, I'm having the same problem. The rest is working flawlessly.

**Comment by AkA57** [comment]
Are you using power saving mode ?

If yes, this is a normal behavior, because the livebox switch off any network communication in power saving mode

**Comment by faizpuru** [comment]
Bingo ! I changed the settings and now it's working.
Thanks.

**Comment by tifou92** [comment]
Same for me.
Thanks !
I close this issue :)
