### ISSUE TITLE
 No module named 'fuzzywuzzy' since 2023.06 update

### ISSUE THREAD

**Issue by Vebryn** [AkA57/liveboxtvuhd#32]
Hi,

This extension is just awesome ! Unfortunately, HASS doesn't start anymore since 2023.06 update: `Platform error media_player.liveboxtvuhd - No module named 'fuzzywuzzy'`

Best regards.

**Comment by AkA57** [comment]
Hi,

fuzzywuzzy was removed on the lastest release.

Thanks for your feedback !
