### ISSUE TITLE
How select a channel ? And power the livebox ?

### ISSUE THREAD

**Issue by mfroger** [AkA57/liveboxtvuhd#33]
Hi,

What are the command to select & specify a channel ? and power on/off the livebox ?

Thanks!

**Comment by thisisbenwoo** [comment]
You need to use a media player. (such as mini-player as recommended in the documentation). From there, you can power and select a channel.

Here's a screenshot from my setup (FR):
![image](https://github.com/AkA57/liveboxtvuhd/assets/45885373/36293289-e4b9-4938-bad2-3de4406a3550)
