### ISSUE TITLE
SOLVED: No show for france

### ISSUE THREAD

**Issue by thisisbenwoo** [AkA57/liveboxtvuhd#34]
Hello,
Thank you for your integration. I've tried quite a few different things, but I can't seem to see the show on the standard media control card or the mini media player card. I'm in France.

For mini-media-player, I get:
![image](https://github.com/AkA57/liveboxtvuhd/assets/45885373/49b447f6-2810-465f-946f-0a3f6beb3940)

For the standard media play, I get:
![image](https://github.com/AkA57/liveboxtvuhd/assets/45885373/8a29b684-445f-4f67-931f-fe379e284522)

Perhaps this is not supported yet for France. Can you advise please. Thank you again!

**Comment by AkA57** [comment]
Hello

Can you try with v1.0.5 ?

**Comment by thisisbenwoo** [comment]
> Hello
> 
> Can you try with v1.0.5 ?

It works!! thank you. FYI, the one thing that seems to be missing/not work/not avail is the ability to go back to the Homepage.
