### ISSUE TITLE
EPG response: 502 Server error

### ISSUE THREAD

**Issue by jeanphic** [AkA57/liveboxtvuhd#37]
Bonjour,
Depuis peu je rencontre cette erreur dans les journaux de homeassistant.
Tout semble fonctionner homis la couverture Artwork qui a disparu.
Je suis en version DOCKER 2023 10.5

-----------------------------------------------------------------------------------------------------------------------------
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.liveboxtvuhd.client
Source: custom_components/liveboxtvuhd/client.py:410
Integration: liveboxtvuhd (documentation)
First occurred: 24 octobre 2023 à 22:45:02 (8 occurrences)
Last logged: 24 octobre 2023 à 22:54:12

EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=446&mco=OFR
EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=78&mco=OFR
EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=458&mco=OFR
EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=1402&mco=OFR
EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=118&mco=OFR

**Comment by ghostsam45** [comment]
Hello,

Same issue : 

EPG response: 502 Server Error: Proxy Error for url: https://rp-live-pc.woopic.com/live-webapp/v3/applications/PC/programs?groupBy=channel&period=current&epgIds=118&mco=OFR

**Comment by AkA57** [comment]
Bonjour,

Merci pour ce retour.
Pouvez-vous tester avec la dernière version ?

**Comment by jeanphic** [comment]
Merci de votre réponse rapide.
Je suis en version v1.0.4. je n'en ai pas vu de plus récente

**Comment by ghostsam45** [comment]
Merci AkA57,

Cela semble être corrigé avec la version 1.0.5

**Comment by jeanphic** [comment]
Le correctif a résolu le problème .
Encore merci pour la réactivité

**Comment by jeanphic** [comment]
et Artwork est de retour
