### ISSUE TITLE
Error when configuring through HACS : No module named 'fuzzywuzzy'

### ISSUE THREAD

**Issue by Imbuzi** [AkA57/liveboxtvuhd#4]
This error is thrown when checking configuration from the liveboxtvuhd module, installed through HACS :

Platform error media_player.liveboxtvuhd - No module named 'fuzzywuzzy'

**Comment by AkA57** [comment]
Merci @Imbuzi pour ton retour.
Je viens d'ajouter fuzzywuzzy en requirement dans la version 0.0.4.
N'hésite pas à me faire un retour si cela ne fonctionne pas

**Comment by larzn** [comment]
Thank you, it's working great now !!!
