### ISSUE TITLE
python-Levenshtein

### ISSUE THREAD

**Issue by LGO44** [AkA57/liveboxtvuhd#40]
I have an error:

Cette erreur provient d'une intégration personnalisée

Logger: py.warnings
Source: custom_components/liveboxtvuhd/client.py:12 
Integration: liveboxtvuhd (documentation) 
First occurred: 22:37:33 (1 occurrences) 
Last logged: 22:37:33

/usr/local/lib/python3.11/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

**Comment by pganansia** [comment]
I have the same issue.
I am using Home Assistant on a docker container and even if I install python-Levenshtein, I will have to reinstall at each container update.

**Comment by AkA57** [comment]
Hi

Thanks for this feedback.
fuzzywuzzy was remove on the lastest release.
