### ISSUE TITLE
New patch proposed to handle remote control entity

### ISSUE THREAD

**Issue by albaintor** [AkA57/liveboxtvuhd#43]
Hi,
I have just submitted a patch to handle the remote entity type : it lets handle the other commands that are not handled by the media player such arrow keys, menu...
https://github.com/AkA57/liveboxtvuhd/pull/42

**Comment by AkA57** [comment]
Thanks for your contribution.
Code has been merged to master branch

**Comment by albaintor** [comment]
Thank you !!
