### ISSUE TITLE
Bouton power 

### ISSUE THREAD

**Issue by legrand76** [AkA57/liveboxtvuhd#44]
Bonjour, 
Le bouton power on off ne fonctionne pas a tous les coups 
Je m'explique si le décodeur est éteint pendant un certain temps ça ne fonctionne plus 
Avez vous le même problème ?

**Comment by albaintor** [comment]
Bonjour, vous avez le nouveau décodeur 6 ? ils ont mis en place un mode éco qui éteint tout.
J'ai râlé sur le forum sans succès pour l'instant : https://communaute.orange.fr/t5/mise-%C3%A0-jour-D%C3%A9codeur-TV4/D%C3%A9codeur-6-d%C3%A9sactiver-le-mode-%C3%A9co/m-p/3178621#M6904

**Comment by AkA57** [comment]
Et oui, même constat, cela vient de la politique d'Orange sur l'économie d'énergie. 
On ne peut rien faire à ce niveau.

**Comment by albaintor** [comment]
Bonjour,

j'ai remonté le problème aux équipes internes chez Orange. Je vais les relancer.
A minima j'ai demandé qu'ils examinent la possibilité d'allumer le décodeur avec un "magic packet" via la fonctionnalité wake on lan. J'ai fait remarquer aussi que leur mode éco avait fait sauter des fonctionnalités de l'application mobile TV d'Orange (plus possible de commander ou streamer depuis l'app mobile).
