### ISSUE TITLE
Adding key 365 for TV guide access

### ISSUE THREAD

**Issue by Kiniou-Bouzou** [AkA57/liveboxtvuhd#46]
Thank you for your integration, very useful

It would be nice to add to the remote commands the key number 365 giving directly access to the TV guide (at least on my TV4 decoder). I have attached the modified const.py file to bring this new key.

[const.py file modified.txt](https://github.com/AkA57/liveboxtvuhd/files/15000044/const.py.file.modified.txt)

**Comment by AkA57** [comment]
Hi @Kiniou-Bouzou ,

This key was added to the lastest version (1.2.0)
