### ISSUE TITLE
I/O inside the event loop

### ISSUE THREAD

**Issue by AkA57** [AkA57/liveboxtvuhd#7]
Hi, component works well (and thanks a lot for that !) but with I/O errors, that appeared with the 109.1 HA update.

Détails du journal ( WARNING )
Logger: homeassistant.util.async_
Source: util/async_.py:120 
First occurred: 2:57:12 (5 occurrences) 
Last logged: 2:57:45

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for liveboxtvuhd doing I/O at custom_components/liveboxtvuhd/client.py, line 56: resp = requests.get(url, params=get_params, timeout=self.timeout)

Thanks for your help

_Originally posted by @Shkrum31 in https://github.com/AkA57/liveboxtvuhd/issues/6#issuecomment-623036883_

**Comment by stonfute** [comment]
Confirm exact same behavior in my setup !

**Comment by AkA57** [comment]
Thanks for this feedback.
This error is now displayed only at startup during platform initialization.
